#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt', '2.4.0'
cookbook 'runit', '1.5.10'
cookbook 'nginx', '2.7.4'
cookbook 'mysql', '5.3.6'
cookbook 'database'
cookbook 'rvm', '0.9.2'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
